### ISSUE TITLE
Сразу можно как доп задачу завести - проверку перед сохранением делать, что все валидно

### ISSUE THREAD

**Issue by Alex-skigo99** [Alex-skigo99/invoice_app#9]
Сразу можно как доп задачу завести - проверку перед сохранением делать, что все валидно

_Originally posted by @tkachenkoas in https://github.com/Alex-skigo99/invoice_app/pull/8#discussion_r1805065904_

**Comment by Alex-skigo99** [comment]
Проверка валидности openapi реализуются тестами. отдельно инструменты либо устарели либо слишком сложны для реализации.

**Comment by tkachenkoas** [comment]
Саша, я не про валидность опенапи, я про валидность данных, которые ты кладешь в базу

Чтобы перед сохранением проверялись:
- длина строковых полей
- значения чисел (положительное/в каких-то границах)
- и все другие бизнес-правила

я не считаю, что это клоузед :)
